name: Java Assignment 2 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download JUnit Jars
      run: |
        curl -O https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.8.1/junit-jupiter-api-5.8.1.jar
        curl -O https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.8.1/junit-jupiter-engine-5.8.1.jar
        curl -O https://repo1.maven.org/maven2/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar

    - name: Compile Java Files
      run: |
        javac -d . -cp ".;junit-jupiter-api-5.8.1.jar;junit-jupiter-engine-5.8.1.jar;apiguardian-api-1.1.2.jar" "Assignment 2/src/LoginApp.java" "Assignment 2/src/LoginAppTest.java"

    - name: Run Tests
      run: |
        java -cp ".;junit-jupiter-api-5.8.1.jar;junit-jupiter-engine-5.8.1.jar;apiguardian-api-1.1.2.jar" org.junit.platform.console.ConsoleLauncher --class-path . --select-class LoginAppTest
